# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ feature/docker-tests ]
  pull_request:
    branches: [ feature/docker-tests ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 setup.py develop
          pip install pytest
          pip install pytest-cov

      - name: Run tests
        run: |
          echo "Starting redis..."
          docker run -d  -p 6379:6379 --name redis redis

          echo "Building eden..."
          docker build . -t eden-test-server

          echo "Running eden..."
          docker run -d -p 127.0.0.1:5656:5656/tcp --name eden-server eden-test-server 

          sleep 10

          echo "Running tests..."
          pytest eden/tests

          echo "Stopping stuff ..."
          docker stop redis
          docker stop eden-server

      # - name: "Upload coverage to Codecov"
      #   uses: codecov/codecov-action@v1
      #   with:
      #     fail_ci_if_error: true
          